#!/usr/bin/env bash
#
# One command for the on-stage demo: put a generated infrastructure change
# on a pull request, ask the gate to apply it to real Scaleway, and follow
# the result.
#
# The point of doing this in one script is that a talk has no room for five
# commands, each with its own way of going wrong in front of an audience.
#
#   make demo-gate                  # replay the recorded generation (default)
#   make demo-gate GENERATE=live    # regenerate with the LLM first (~76s)
#   make demo-gate DEMO_YES=1       # skip the confirmation prompt
#
# This SPENDS MONEY: it applies to real Scaleway. A run provisions one
# project and one 10GB block volume for about a minute.
set -euo pipefail

SCENARIO="${DEMO_SCENARIO:-block-paris}"
GENERATE="${GENERATE:-replay}"
LABEL="layer3-gate"
RECORDED="docs/demo/recorded-generation/${SCENARIO}"
FIXTURE="examples/layer3-gate/${SCENARIO}"

die() { printf '\n\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }
say() { printf '\n\033[36m▸ %s\033[0m\n' "$*"; }

# ---- preflight -------------------------------------------------------
# Every one of these has a failure mode that is embarrassing on stage and
# trivial to check beforehand.
say "Preflight"

command -v gh >/dev/null || die "gh is not installed"
gh auth status >/dev/null 2>&1 || die "gh is not authenticated — run: gh auth login"

git rev-parse --git-dir >/dev/null 2>&1 || die "not a git repository"
[ -z "$(git status --porcelain)" ] || die "working tree is dirty — commit or stash first"

branch=$(git rev-parse --abbrev-ref HEAD)
[ "$branch" = "main" ] || die "run this from main (currently on $branch)"

gh label list --limit 200 2>/dev/null | grep -q "^${LABEL}" \
  || die "no '${LABEL}' label in this repo — the gate is triggered by it"

[ -d "$FIXTURE" ] || die "no gate fixture directory at $FIXTURE"
[ -f "$FIXTURE/.terraform.lock.hcl" ] \
  || die "no trusted lock file at $FIXTURE/.terraform.lock.hcl — the gate refuses to run without one"

echo "  gh authenticated, tree clean, on main, label present, fixture and lock in place"

# ---- confirm ---------------------------------------------------------
if [ "${DEMO_YES:-0}" != "1" ]; then
  printf '\nThis applies to REAL Scaleway and spends money. Continue? [y/N] '
  read -r reply
  case "$reply" in [yY]*) ;; *) die "aborted" ;; esac
fi

# ---- the agent's change ----------------------------------------------
stamp=$(git rev-parse --short HEAD)-$$
work="demo/gate-${SCENARIO}-${stamp}"

if [ "$GENERATE" = "live" ]; then
  say "Generating ${SCENARIO} with the LLM (this is the slow half — 40-90s)"
  command -v ./bin/infrafactory >/dev/null 2>&1 || go build -o ./bin/infrafactory ./cmd/infrafactory
  ./bin/infrafactory generate "scenarios/training/${SCENARIO}.yaml"
  src=$(./bin/infrafactory --output json generate "scenarios/training/${SCENARIO}.yaml" 2>/dev/null \
        | python3 -c 'import json,sys; print(json.load(sys.stdin).get("output_dir",""))' 2>/dev/null || true)
  [ -n "$src" ] && [ -d "$src" ] || src="output/${SCENARIO}"
  [ -d "$src" ] || die "generation produced no output directory"
else
  say "Replaying the recorded generation"
  [ -d "$RECORDED" ] || die "no recorded generation at $RECORDED"
  src="$RECORDED"
fi

say "Staging the change on ${work}"
git checkout -q -b "$work"
cp "$src"/*.tf "$FIXTURE/"
git add "$FIXTURE"
if git diff --cached --quiet; then
  # Nothing changed, so the PR would be empty and the gate would have
  # nothing to prove. Nudge one file rather than fail: on stage, the
  # demo is the point, not the diff.
  printf '\n# demo run %s\n' "$stamp" >> "$FIXTURE/main.tf"
  git add "$FIXTURE"
fi
git commit -q -m "demo: apply the generated ${SCENARIO} change through the Layer 3 gate"
git push -q -u origin "$work"

# ---- the pull request ------------------------------------------------
say "Opening the pull request"
pr_url=$(gh pr create \
  --title "demo: ${SCENARIO} through the real-cloud gate" \
  --body "$(cat <<BODY
Generated by \`infrafactory generate scenarios/training/${SCENARIO}.yaml\` and put through the Layer 3 gate.

Applying the \`${LABEL}\` label asks the gate to deploy this to **real Scaleway**, probe it, destroy it, sweep the account, and comment the result below — before this merges.

The apply waits on a deployment approval. That approval is the point.
BODY
)")
echo "  $pr_url"
pr_number=$(basename "$pr_url")

say "Applying the '${LABEL}' label"
gh pr edit "$pr_number" --add-label "$LABEL"

cat <<EOF

  The gate is now waiting on YOUR approval — it will not apply anything until
  you approve the deployment:

    ${pr_url}

  Approve there, or with:  gh api -X POST repos/{owner}/{repo}/actions/runs/<id>/deployment_protection_rule

EOF

say "Watching the run"
sleep 5
run_id=$(gh run list --workflow=layer3-gate.yml --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)
if [ -n "$run_id" ]; then
  gh run watch "$run_id" --exit-status || true
fi

say "Gate comment"
gh api "repos/{owner}/{repo}/issues/${pr_number}/comments" \
  --jq '.[-1].body' 2>/dev/null || echo "  (no comment yet)"

cat <<EOF

  Done. The change was applied to real Scaleway and destroyed again.
  You merge:  gh pr merge ${pr_number} --squash

EOF
